apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: amalspillai02/order-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/orders
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 5002
      targetPort: 5002
