apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: DB_NAME
              value: orders
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
