pipeline {
  agent any

  environment {
    IMAGE_NAME = 'amalspillai02/product-service:latest'
    KUBECONFIG = '/var/lib/jenkins/.kube/config'
  }

  stages {
    stage('Build Docker Image') {
      steps {
        script {
          sh 'docker build -t $IMAGE_NAME product-service'
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh """
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME
          """
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        withEnv(["KUBECONFIG=$KUBECONFIG"]) {
          sh 'kubectl apply -f k8s/product/'
        }
      }
    }
  }
}
