pipeline {
    agent any

    environment {
        IMAGE_NAME = 'amalspillai02/auth-service'
        TAG = 'latest'
        AWS_REGION = 'ap-southeast-1'
        EKS_CLUSTER_NAME = 'devops-eks-cluster'
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $IMAGE_NAME:$TAG auth-service'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }

        stage('Deploy to AWS EKS') {
            steps {
                script {
                    // 1. Configure AWS Credentials
                    withCredentials([aws(credentialsId: 'aws-creds')]) {
                        // 2. Update kubeconfig for EKS
                        sh 'aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME'
                        sh 'kubectl apply -f k8s/db/'
                        sh 'kubectl apply -f k8s/auth/'
                    }
                }
            }
        }
    }
}