pipeline {
  agent any

  environment {
    IMAGE_NAME = "amalspillai02/auth-service"
    TAG = "latest"
  }

  stages {
    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          sh 'docker build -t $IMAGE_NAME:$TAG auth-service'
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:$TAG
          '''
        }
      }
    }

    stage('Deploy to Minikube') {
  steps {
    withEnv(["KUBECONFIG=/home/your-username/.kube/config"]) {
      sh 'kubectl apply -f k8s/auth/'
    }
  }
}

  }
}
