apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: amalspillai02/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/product
